<?php

namespace AppBundle\Repository;

/**
 * FeddbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeddbackRepository extends \Doctrine\ORM\EntityRepository
{
}
